name: Github-actions-practice

on:
  push:
    branches:
    - main

jobs:
  demo:
    name: demo-job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Greeting
      run: echo "Hello Actions"
    
    - name: Inline
      run: ls
